version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["daphne", "taskmanager.asgi:application"]
    depends_on:
      - web
