name: Deploy Django Task Manager

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy --stack-name TaskManagerStack --template-body file://cloudformation.yaml --capabilities CAPABILITY_NAMED_IAM --region us-east-1
        working-directory: .github/workflows

      - name: Get EC2 Public IP
        id: ec2-info
        run: |
          public_ip=$(aws ec2 describe-instances --filters "Name=tag:aws:cloudformation:stack-name,Values=TaskManagerStack" --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "Public IP: $public_ip"
          echo "::set-output name=public_ip::$public_ip"
        working-directory: .github/workflows

      - name: Run Ansible Playbook
        env:
          EC2_PUBLIC_IP: ${{ steps.ec2-info.outputs.public_ip }}
        run: |
          echo "EC2 Public IP: $EC2_PUBLIC_IP"
          ansible-playbook -i $EC2_PUBLIC_IP, deploy_taskmanager.yml
        working-directory: .github/workflows
